name: HW 2
on: push
jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Test event
      # https://stackoverflow.com/a/59536836
      run: |
        echo "Push event received!"
        echo "before = ${{ github.event.before }}"
        echo "after = ${{ github.event.after }}"
        echo "sub before = $(git rev-parse ${{ github.event.before }})"
        echo "sub after = $(git rev-parse ${{ github.event.after }})"
