name: HW 2
on: push
jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test event
      # https://stackoverflow.com/a/59536836
      env:
        PREV: ${{ github.event.before }}
        NEW: ${{ github.event.after }}
      shell: bash
      run: |
        echo "Push event received!"
        echo "before = $PREV"
        echo "after = $NEW"

    - name: Conditional test
      shell: bash
      run: |
        SUB_PREV=$(git rev-parse $PREV:linux)
        SUB_NEW=$(git rev-parse $NEW:linux)
        echo "sub before = $SUB_PREV"
        echo "sub after = $SUB_NEW"
        if [[ $SUB_PREV != $SUB_NEW ]]; then echo "Changed!"; done
