name: HW 2
on:
  push:
    paths:
    - "linux"

jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: ./install-deps.sh

    - name: Get linux submodule
      shell: bash
      run: |
        COMMIT=$(git rev-parse HEAD:linux)
        echo "linux commit: $COMMIT"
        wget -q "https://github.com/JHH20/linux/archive/${COMMIT}.zip"

    - name: Build linux kernel
      shell: bash
      run: |
        unzip -q *.zip -d linux
        echo "Begin building the kernel"
        ./build-linux.sh linux/* tinyconfig
