name: HW 2
on:
  push:
    paths:
    - "linux"

jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get linux submodule
      shell: bash
      run: |
        COMMIT=$(git rev-parse HEAD:linux)
        echo "linux commit: $COMMIT"
        wget "https://github.com/JHH20/linux/archive/${COMMIT}.zip"

    - name: Build linux kernel
      shell: bash
      run: |
        unzip *.zip -d linux
        ./build-linux.sh linux tinyconfig
