name: HW 2
on: push
jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test event
      # https://stackoverflow.com/a/59536836
      env:
        PREV: ${{ github.event.before }}
        NEW: ${{ github.event.after }}
      run: |
        echo "Push event received!"
        echo "before = $PREV"
        echo "after = $NEW"

    - name: Conditional test
      if: env.PREV != env.NEW
      run: |
        echo "$PREV != $NEW"
        echo "sub before = $(git rev-parse $PREV)"
        echo "sub after = $(git rev-parse $NEW)"
