name: HW 2 Part C-2
on:
  push:
    paths:
    - "test"

jobs:
  compile-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile Test
      shell: bash
      run: |
        cd test
        make
